trigger:
  branches:
    include:
      - "*"
  tags:
    include:
      - "*"

name: $(BuildID)-$(Build.SourceBranchName)

resources:
- repo: self

variables:
  ${{ if notIn(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    dockerCommand: build
    deployService: false
    deployEnvironment: "no"
    imageTags: "no"
    serviceName: "no"
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    dockerCommand: buildAndPush
    deployService: true
    deployEnvironment: production
    imageTags: |
      $(Build.BuildId)
      latest
    serviceName: geohelper_proxy

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: buildAndPushDockerImages
    displayName: Build and push Docker images
    jobs:
      - job: buildPublicImage
        displayName: Build public docker image
        steps:
          - task: Docker@2
            displayName: Build image for docker hub
            inputs:
              containerRegistry: 'rtuitlab connection by admin'
              repository: 'rtuitlab/geohelper-proxy'
              command: '${{ variables.dockerCommand }}'
              Dockerfile: '$(Build.SourcesDirectory)/Proxy/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)/Proxy'
              tags: ${{ variables.imageTags }}
              addPipelineData: false
      - job: buildPrivateImage
        displayName: Build private docker image
        steps:
          - task: Docker@2
            displayName: Build image for private docker registry
            inputs:
              containerRegistry: 'private rtuitlab registry'
              repository: 'geohelper/proxy'
              command: '${{ variables.dockerCommand }}'
              Dockerfile: '$(Build.SourcesDirectory)/Proxy/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)/Proxy'
              tags: ${{ variables.imageTags }}
              addPipelineData: false
  - stage: Deploy
    displayName: Deploy service
    condition: and(succeeded(), ${{ variables.deployService }})
    jobs:
      - deployment: Deploy
        environment: ${{ variables.deployEnvironment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - download: none
                - task: SSH@0
                  inputs:
                    sshEndpoint: 'swarm manager'
                    runOptions: 'commands'
                    commands: 'docker service update --image registry.rtuitlab.dev/geohelper/proxy:$(Build.BuildId) ${{ variables.serviceName }} --with-registry-auth'
                    readyTimeout: '20000'
