trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'rtuitlab connection by admin'
        repository: 'rtuitlab/geohelper-proxy'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Proxy/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/Proxy'
        tags: |
          $(tag)
          latest
        addPipelineData: false