trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'rtuitlab connection by admin'
        repository: 'rtuitlab/geohelper-proxy'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Proxy/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/Proxy'
        tags: |
          $(tag)
          latest
        addPipelineData: false
- stage: Deploy
  displayName: Deploy service
  jobs:
  - job: Deploy
    steps:
    - task: SSH@0
      inputs:
        sshEndpoint: 'swarm manager'
        runOptions: 'commands'
        commands: 'docker service update --image rtuitlab/geohelper-proxy:$(tag) geohelper_proxy'
        readyTimeout: '20000'
