version: '3.8'

services:
  proxy:
    networks:
    - net
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 50M
        reservations:
          cpus: '0.05'
          memory: 20M
    logging:
      driver: "json-file"
      options:
          max-size: "200k"
          max-file: "10"
  front:
    networks:
    - net
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 50M
        reservations:
          cpus: '0.05'
          memory: 20M
    logging:
      driver: "json-file"
      options:
          max-size: "200k"
          max-file: "10"
  back:
    networks:
    - net
networks:
  net:
    driver: overlay
